apiVersion: v1
kind: Namespace
metadata:
  name: restar

---
# kkt driver
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kkt-service
  name: kkt-service
  namespace: restar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kkt-service
  template:
    metadata:
      labels:
        app: kkt-service
    spec:
      containers:
        - image: ghcr.io/re-star-ru/shtrih-m-driver:latest
          name: kkt-service
          resources:
            limits:
              memory: "128M"
              cpu: "200m"
          ports:
            - containerPort: 8080
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: kkt-service
  namespace: restar
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kkt-service

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kkt-service
  namespace: restar
spec:
  virtualhost:
    fqdn: api.re-star.ru
    tls:
      secretName: kube-system/re-star-ru-wildcard
  routes:
    - conditions:
        - prefix: /v1/kkt
      pathRewritePolicy:
        replacePrefix:
          - replacement: /
      services:
        - name: kkt-service
          port: 8080
