### get status json
GET http://localhost:8080/status?json
Accept: application/json

### get status
GET http://localhost:8080/status
Accept: application/json

### test print
POST http://localhost:8080/printPackage
Content-Type: application/json

{
  "SM-N": {
    "cashierINN": "262804786800",
    "operations": [
      {
        "type": "income",
        "subject": "goods",
        "price": 0,
        "amount": 0,
        "sum": 0,
        "name": "тест test"
      }
    ],
    "cash": 0,
    "digital": 0,
    "rounding": 0,
    "taxSystem": "PSN",
    "notPrint": true
  },
  "EV-N": {
    "cashierINN": "123456789012",
    "operations": [
      {
        "type": "income",
        "subject": "service",
        "amount": 0,
        "sum": 0,
        "name": "тест test"
      }
    ],
    "cash": 0,
    "digital": 0,
    "rounding": 0,
    "taxSystem": "PSN",
    "notPrint": true
  }
}
