@startuml

start

:Проверка на открытую смену;

if (Смена открыта?) then (Да)
  :Открыть чек;
  :Добавить строку товара;
  :Закрыть чек;
else (Нет)
  :Вернуть ошибку
  о закрытой смене;
  stop
endif

stop

@enduml