@startuml

start

:Проверка режима кассы;

if (Режим кассы
2, Смена открыта?) then (Да)
  :ок Добавить операцию v2
  продажа, возвра продажи,
  покупка, возврат покупки.;
  :Закрыть чек v2;
else (Нет)
  :Вернуть ошибку
  о неверном
  режиме кассы;
  stop
endif

stop

@enduml