name: ci
on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

      # TAG: ${{github.sha}}
      # GITHUB_SHA: ${{github.sha}}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Setup Nomad
        uses: rluisr/nomad-actions@master

      - name: Deploy
        env:
          TAG: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          NOMAD_ADDR: https://nomad.re-star.ru
          # NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}

        run: |
          envsubst \${IMAGE_NAME},\${TAG} < service.nomad > job.nomad
          nomad job run job.nomad

      # - name: Deploy with Nomad
      #   env:
      #     NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      #     NOMAD_ADDR: https://nomad.re-star.ru
      #   uses: docker://hashicorp/levant:latest
      #   with:
      #     args: levant deploy
      #       -var "tag=${{github.sha}}"
      #       -var "repo=${{github.repository}}"
      #       service.hcl

      #       envsubst '${REPO}, ${TAG}' < service.nomad > jo.nomad

      # - name: Deploy with Nomad
      #   env:
      #     NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      #     NOMAD_ADDR: https://nomad.re-star.ru
      #   uses: docker://hashicorp/levant:latest

      #   with:
      #     args: levant deploy
      #       -var "tag=${{github.sha}}"
      #       -var "repo=${{github.repository}}"
      #       service.hcl

      # - name: Deploy with kube-tools
      #   uses: stefanprodan/kube-tools@v1
      #   env:
      #     KUBECONFIG: .kubeconfig
      #     UPDATE: .deploy.yaml
      #   with:
      #     command: |
      #       cd kube
      #       kustomize edit set image ghcr.io/${REPO}:latest=ghcr.io/${REPO}:${GITHUB_SHA}
      #       cat kustomization.yaml
      #       kustomize build . > $UPDATE
      #       echo "${{secrets.KUBE_CONFIG}}" > $KUBECONFIG
      #       kubectl apply -f $UPDATE
